development:
  adapter: postgresql
  encoding: unicode
  database: overtime
  pool: 5
  username: john
  password: shema

test:
  adapter: postgresql
  encoding: unicode
  database: overtime_test
  pool: 5
  username: john  
  password: shema

production:
  adapter: postgresql
  encoding: unicode
  database: overtime_production
  pool: 5
  username: john  
  password: shema
