development:
  adapter: postgresql
  encoding: unicode
  database: overtime
  pool: 5
  username: john
  password: shema  
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  database: overtime_test
  pool: 5
  username: john  
  password: shema
  template: template0

production:
  adapter: postgresql
  encoding: unicode
  database: overtime_production
  pool: 5
  username: john  
  password: shema
